name: Publish crate
run-name: Publishing crate by @${{ github.actor }}
on:
  release:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to homebrew
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build binaries
      - run: cargo build --release

      - name: Run packaging script
        run: ./.github/scripts/package-homebrew-release.sh
        shell: bash
