name: Publish to homebrew
run-name: Publishing by @${{ github.actor }}
on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]

jobs:
  publish:
    name: Publish to homebrew
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build binaries
        run: cargo build --release

      - name: Run packaging script
        run: |
         chmod +x ./.github/scripts/prepare-homebrew-package.sh
         ./.github/scripts/prepare-homebrew-package.sh
        shell: bash

      - name: Get version
        id: get-version-job
        run: |
         chmod +x ./.github/scripts/get-version.sh
         ./.github/scripts/get-version.sh 
        
      - name: Making release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.DRO_RELEASE_TOKEN }}"
          automatic_release_tag: "${{ steps.get-version-job.outputs.CURRENT_VERSION }}"
          title: "Homebrew release for ${{ steps.get-version-job.outputs.CURRENT_VERSION }}"
          prerelease: false
          files: 
            dro-mac.tar.gz
