name: Publish to homebrew
run-name: Publishing by @${{ github.actor }}
on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]

jobs:
  publish:
    name: Publish to homebrew
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Build binaries
        run: cargo build --release

      - name: Run packaging script
        id: packaging-script
        run: |
          chmod +x ./.github/scripts/prepare-homebrew-package.sh
          ./.github/scripts/prepare-homebrew-package.sh
        shell: bash

      - name: Get version
        id: get-version-job
        run: |
          chmod +x ./.github/scripts/get-version.sh
          ./.github/scripts/get-version.sh >> $GITHUB_OUTPUT
        
      - name: Making release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.DRO_RELEASE_TOKEN }}"
          automatic_release_tag: "${{ steps.get-version-job.outputs.CURRENT_VERSION }}"
          title: "Homebrew release for ${{ steps.get-version-job.outputs.CURRENT_VERSION }}"
          prerelease: false
          files: 
            dro-mac.tar.gz


      - name: Bump Brew
        env: 
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.BREW_TOKEN }}
        run: |
          brew tap extrawurst/tap
          brew bump-formula-pr -f --version=${{ steps.get_version.outputs.version }} --no-browse --no-audit \
          --sha256=${{ steps.shasum.outputs.sha }} \
          --url="https://github.com/anthonwellsjo/dro/releases/download/${{ steps.get-version-job.outputs.CURRENT_VERSION }}/dro-mac.tar.gz" \
          extrawurst/tap/gitui

      # - name: Create formula
      #   run: |
      #     echo "${{ steps.packaging-script.outputs.sha256 }}"
      #     chmod +x ./.github/scripts/create-homebrew-formula.sh
      #     ./.github/scripts/create-homebrew-formula.sh
      #   shell: bash
